language: lisp
sudo: required

git:
  depth: 3

env:
  matrix:
    #- LISP=abcl
    #- LISP=allegro
    - LISP=sbcl COVERALLS=true
    - LISP=ccl
    - LISP=clisp
    #- LISP=ecl

matrix:
  allow_failures:
    - env: LISP=clisp

install:
  #- ./install.sh
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash  
  - git clone https://github.com/tgutu/clunit.git ~/lisp/clunit
  - git clone https://github.com/fukamachi/cl-coveralls ~/lisp/cl-coveralls
    
script:
  - cl -l clunit -l cl-coveralls
       -l array-operations -l 'array-operations/tests'
       -e '(coveralls:with-coveralls (:exclude (list "tests"))
             (let ((report (array-operations/tests:run)))
               (when (plusp (slot-value report (quote clunit::failed)))
                 (princ report)
                 (uiop:quit 1))))'
