language: lisp
sudo: required

env:
  matrix:
    #- LISP=abcl
    #- LISP=allegro
    - LISP=sbcl
    - LISP=ccl
    #- LISP=clisp
    #- LISP=ecl

matrix:
  allow_failures:
    - env: LISP=ccl

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh  
    
script:
  - cl -e "(ql:quickload :array-operations)
           (ql:quickload :array-operations-tests)
           (when
             (plusp
               (slot-value (array-operations-tests:run)
                           'clunit::failed))
             (uiop:quit 1))"
  
